### ISSUE TITLE
Create User Story

### ISSUE THREAD

**Issue by ismailsunni** [ismailsunni/MasterThesis#9]
- [x] As a user who has geospatial R script and wants to run a benchmark among R implementation and platform
- [x] A an R package developer who wants to test his/her package in different R implementation and platform

**Comment by nuest** [comment]
Suggestion for more typical user story phrasing, adding the motivation in the "so that" part

- As a _user_, _I want to_ run my geospatial workflow based on R across different R implementations and Linux distributions, _so that_ I lean which one works and which is the fastest one.
- As a _user_, _I want to_ install and test my own R package on different R implementations, _so that_ I know what problems exists on platforms different from my own and can support a broader user base.

**Comment by ismailsunni** [comment]
Final User Story:

- _As an_ R package developer, _I want_ to test my R package across different R implementations and platform, _so that_ I know for what problem in those R implementation and platform for my R package and can support a boarder user base.

- _As an_ R user, _I want_ to run a benchmark for my geospatial workflow in R across different R implementations and platform _so that_ I know which one that can work and which one is the fastest one.
